scdf-type:
  oss:
    release: '2.10.3'
    snapshot: '2.11.0-SNAPSHOT'
    maintenance-snapshot: '2.10.4-SNAPSHOT'
  pro:
    release: '1.5.3'
    snapshot: '1.6.0-SNAPSHOT'
    maintenance-snapshot: '1.5.4-SNAPSHOT'
default:
  scdf-type: 'oss'
  version: 'release'
  package-version: |-
    Downloading https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.3/apache-maven-3.8.3-bin.zip
    ........................................................................................................................................................................................................................................................................................................................................................................................................................................................................
    Unzipping /home/runner/.m2/wrapper/dists/apache-maven-3.8.3-bin/5a6n1u8or3307vo2u2jgmkhm0t/apache-maven-3.8.3-bin.zip to /home/runner/.m2/wrapper/dists/apache-maven-3.8.3-bin/5a6n1u8or3307vo2u2jgmkhm0t
    Set executable permissions for: /home/runner/.m2/wrapper/dists/apache-maven-3.8.3-bin/5a6n1u8or3307vo2u2jgmkhm0t/apache-maven-3.8.3/bin/mvn
    2.11.0-RC1
